### ISSUE TITLE
Mention extension to dominance in the conclusion

### ISSUE THREAD

**Issue by jeromekelleher** [daikitag/tstrait-paper#12]
We assume the additive model, but we should support non-additive also longer term.

Papers to cite:
- https://www.science.org/doi/full/10.1126/science.abn8455

**Comment by daikitag** [comment]
Even though this is already cited in that paper, this is also a good one to cite:
- https://www.nature.com/articles/ng.3285
Many people are using this paper as a justification to use the additive model in GWAS.

**Comment by daikitag** [comment]
This is my feedback based on what I read the draft of the paper, but given the amount of space that we have, I'm not sure if it would be worthwhile for us to explain dominance. There are still many characteristics of quantitative trait simulation that we need to include, which includes dominance, epistasis, genetic x environmental interaction, linkage disequilibirium, pedigree, etc, and the list will become long.
Instead, I think it might be worthwhile to add a single sentence at the conclusion saying:
"We have created the tstrait package as a foundation block of quantitative trait simulation for ARGs. We plan to further implement various features of quantitative trait simulation in the future releases."

**Comment by jeromekelleher** [comment]
Good point, let's see how it works out.
