### ISSUE TITLE
Report RAM usage as well as time

### ISSUE THREAD

**Issue by jeromekelleher** [daikitag/tstrait-paper#7]
I think the scaling figure would be much more interesting if we reported RAM usage in the second panel.

Then, we just run *one* simulation on the French canadian dataset and report its time and memory usage in the text, and do the same for the 1000G tree.

That's all we need

**Comment by jeromekelleher** [comment]
Looking in to how we do this with memray (which is pretty cool)

**Comment by jeromekelleher** [comment]
I tried to do this, but it's actually really hard to get accurate numbers because usage is so small. So, I don't think it's worth the bother, and we can just say "we did all this on a laptop"

**Comment by daikitag** [comment]
Thank you very much @jeromekelleher . I was planning to do this, but I really thank you for doing this.
